In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# prepare input data
def prepare_inputs(X_train, X_test):
    oe = OrdinalEncoder()
    oe.fit(['丽丽','东东'])
    X_train_enc = oe.transform(X_train)
    X_test_enc = oe.transform(X_test)
    return X_train_enc, X_test_enc

# prepare target
def prepare_targets(y_train, y_test):
    le = LabelEncoder()
    le.fit(y_train)
    y_train_enc = le.transform(y_train)
    y_test_enc = le.transform(y_test)
    return y_train_enc, y_test_enc

dataset = []

for i in range(100000):
    if i % 2 == 0:
        dataset.append(('丽丽', '美女'))
    else:
        dataset.append(('东东', '丑男'))

images = [x[0] for x in dataset]
labels = [x[1] for x in dataset]

# print(images)
# print(labels)

train_images = [[x] for x in images[:90000]]
test_images = [[x] for x in images[90000:]]
train_labels = [[x] for x in labels[:90000]]
test_labels = [[x] for x in labels[90000:]]

print(train_images[:10])
print(test_images[:10])
print(train_labels[:10])
print(test_labels[:10])

# train_images = np.array(train_images)
# test_images = np.array(test_images)
# train_labels = np.array(train_labels)
# test_labels = np.array(test_labels)

train_images, test_images = prepare_targets(train_images, test_images)
train_labels, test_labels = prepare_targets(train_labels, test_labels)

print(train_images.shape)

print(train_images[:10])
print(test_images[:10])
print(train_labels[:10])
print(test_labels[:10])


[['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东']]
[['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东']]
[['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男']]
[['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男']]
(90000,)
[1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0]


In [42]:
import keras
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(1,), activation='relu'),
    keras.layers.Dense(10, input_shape=(10,), activation='relu'),
    keras.layers.Dense(5, input_shape=(10,), activation='tanh'),
    keras.layers.Dense(1, input_shape=(5,), activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
epochs_num = 3
acc_list = []
for i in range(epochs_num):
    model.fit(train_images, train_labels, epochs=1)
    test_labels = model.predict(test_images)
    print('y_predicted',y_predicted[:10])
    loss, acc = model.evaluate(test_images, test_labels, verbose=1)
    print('loss, acc',loss, acc)
    print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))
    acc_list.append('Restored model, accuracy: {:5.2f}%'.format(100 * acc))
    




Epoch 1/1
90000/90000 [==============================] - 5s 53us/step - loss: 0.0486 - acc: 0.9966
y_predicted [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
10000/10000 [==============================] - 0s 43us/step
loss, acc 0.010717183381319046 0.0
Restored model, accuracy:  0.00%
Epoch 1/1
90000/90000 [==============================] - 4s 41us/step - loss: 6.7090e-04 - acc: 1.0000
y_predicted [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
10000/10000 [==============================] - 0s 20us/step
loss, acc 0.002510080175846815 0.0
Restored model, accuracy:  0.00%
Epoch 1/1
90000/90000 [==============================] - 4s 45us/step - loss: 1.4378e-04 - acc: 1.0000
y_predicted [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
10000/10000 [==============================] - 0s 17us/step
loss, acc 0.0006896704941987992 0.0
Restored model, accuracy:  0.00%


In [41]:
for i in range(10):
    print(float(y_predicted[i]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [37]:
for i in range(10):
    print(float(test_images[i]))

1.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0


In [38]:
weights = model.get_weights()  # Getting params
print(weights)

[array([[1.4954952]], dtype=float32), array([0.00022079], dtype=float32), array([[ 0.82876295, -0.7233846 ,  1.0769264 ,  0.18030828, -0.33293957,
         1.0609071 , -0.67064065,  0.09725069,  0.35551247, -0.5458601 ]],
      dtype=float32), array([-0.00021434,  0.        , -0.00039031, -0.19216721,  0.        ,
       -0.00034495,  0.        , -0.14547177, -0.14291328,  0.        ],
      dtype=float32), array([[ 0.5785333 ,  0.61402   ,  0.9758075 , -1.180516  ,  0.13474596],
       [ 0.0917142 ,  0.5661823 , -0.35567874, -0.3122584 , -0.1599639 ],
       [ 0.26919433,  0.5524103 ,  0.24138781, -0.9662528 , -0.77027136],
       [ 0.48344263, -0.07243299, -0.22049738,  0.39936495, -0.07944354],
       [ 0.5380741 ,  0.12155974,  0.3962707 , -0.2733248 , -0.01104754],
       [ 1.0362929 ,  0.73557633,  0.56430644,  0.09725711, -0.86872166],
       [ 0.5342855 ,  0.0688042 , -0.30047044,  0.36104006, -0.00345594],
       [-0.46089447, -0.2339591 , -0.48476782, -0.20307265,  0.35871467

In [1]:
eva = model.evaluate(test_images, test_labels)
print(eva)

model.save('./ws_model1.h5')

model.summary()

weights = model.get_weights()  # Getting params
print(weights)

a_weights = [np.array([[0.0155494]], dtype='float32'),np.array([0.5], dtype='float32')]
print(a_weights)
# model.set_weights(a_weights)


y_predicted = model.predict(test_images)
print(test_images[:20])
print(y_predicted[:20])

NameError: name 'model' is not defined

In [11]:
y_predicted = model.predict(test_images)
y_pre_0_1 = [1 if x >0.5 else 0 for x in y_predicted]
print(test_images[:20])
print(y_predicted[:20])
print(y_pre_0_1[:20])

[0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
