In [1]:
# load the dataset as a pandas DataFrame
# load and summarize the dataset
# example of ordinal encoding for a neural network
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

filename = r'./breast-cancer.csv'
data = read_csv(filename, header=None)
# retrieve numpy array
dataset = data.values

# split into input (X) and output (y) variables
X = dataset[:, :-1]
y = dataset[:, -1]

# format all fields as string
X = X.astype(str)
# reshape target to be a 2d array
y = y.reshape((len(y), 1))


# load the dataset
def load_dataset(filename):
	# load the dataset as a pandas DataFrame
	data = read_csv(filename, header=None)
	# retrieve numpy array
	dataset = data.values
	# split into input (X) and output (y) variables
	X = dataset[:, :-1]
	y = dataset[:, -1]
	# format all fields as string
	X = X.astype(str)
	# reshape target to be a 2d array
	y = y.reshape((len(y), 1))
	return X, y


...
# load the dataset
X, y = load_dataset('breast-cancer.csv')
# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

# load and summarize the dataset
from pandas import read_csv
from sklearn.model_selection import train_test_split



# load the dataset
X, y = load_dataset('breast-cancer.csv')
# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

print(type(X_train))
# summarize
print('Train', X_train.shape, y_train.shape)
print('Test', X_test.shape, y_test.shape)


# prepare input data
def prepare_inputs(X_train, X_test):
	oe = OrdinalEncoder()
	oe.fit(X_train)
	X_train_enc = oe.transform(X_train)
	X_test_enc = oe.transform(X_test)
	return X_train_enc, X_test_enc


# prepare target
def prepare_targets(y_train, y_test):
	le = LabelEncoder()
	le.fit(y_train)
	y_train_enc = le.transform(y_train)
	y_test_enc = le.transform(y_test)
	return y_train_enc, y_test_enc



<class 'numpy.ndarray'>
Train (191, 9) (191, 1)
Test (95, 9) (95, 1)


In [2]:
...
# prepare input data
X_train_enc, X_test_enc = prepare_inputs(X_train, X_test)
# prepare output data
y_train_enc, y_test_enc = prepare_targets(y_train, y_test)

d:\python\python36\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [5]:
import keras
from keras.layers import Dense

# define the model
model = keras.Sequential()
model.add(Dense(9, input_dim=X_train_enc.shape[1], activation='relu', kernel_initializer='he_normal'))
model.add(Dense(9, input_dim=X_train_enc.shape[1], activation='relu', kernel_initializer='he_normal'))
model.add(Dense(9, input_dim=X_train_enc.shape[1], activation='relu', kernel_initializer='he_normal'))
model.add(Dense(9, input_dim=X_train_enc.shape[1], activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(X_train_enc, y_train_enc, epochs=100, batch_size=16, verbose=1)

Epoch 1/100
191/191 [==============================] - 0s 2ms/step - loss: 0.6591 - acc: 0.7277
Epoch 2/100
191/191 [==============================] - 0s 105us/step - loss: 0.6368 - acc: 0.7277
Epoch 3/100
191/191 [==============================] - 0s 115us/step - loss: 0.6217 - acc: 0.7277
Epoch 4/100
191/191 [==============================] - 0s 105us/step - loss: 0.6120 - acc: 0.7277
Epoch 5/100
191/191 [==============================] - 0s 120us/step - loss: 0.6045 - acc: 0.7277
Epoch 6/100
191/191 [==============================] - 0s 115us/step - loss: 0.5965 - acc: 0.7277
Epoch 7/100
191/191 [==============================] - 0s 105us/step - loss: 0.5917 - acc: 0.7277
Epoch 8/100
191/191 [==============================] - 0s 126us/step - loss: 0.5845 - acc: 0.7277
Epoch 9/100
191/191 [==============================] - 0s 120us/step - loss: 0.5789 - acc: 0.7277
Epoch 10/100
191/191 [==============================] - 0s 131us/step - loss: 0.5735 - acc: 0.7277
Epoch 11/100
191/191 

In [20]:
print(X_test_enc[:10])
print(y_test_enc[:10])

[[3. 2. 4. 4. 1. 2. 0. 1. 1.]
 [3. 2. 5. 4. 1. 1. 0. 1. 1.]
 [3. 2. 7. 0. 0. 1. 0. 2. 0.]
 [2. 2. 3. 4. 1. 1. 1. 4. 1.]
 [1. 2. 0. 0. 0. 1. 1. 0. 0.]
 [1. 2. 6. 0. 0. 2. 0. 1. 0.]
 [2. 2. 5. 4. 0. 1. 1. 2. 0.]
 [1. 2. 3. 4. 1. 1. 1. 2. 1.]
 [4. 0. 2. 0. 0. 1. 1. 2. 0.]
 [3. 0. 5. 4. 0. 2. 1. 2. 0.]]
[1 0 0 1 1 1 1 0 0 1]


In [25]:
# evaluate the keras model
_, accuracy = model.evaluate(X_test_enc, y_test_enc, verbose=0)
print(_)
print('Accuracy: %.2f' % (accuracy * 100))

y_predicted = model.predict(X_test_enc[:10])
print('y_predicted',y_predicted[:10])

0.750290754594301
Accuracy: 66.32
y_predicted [[6.1089647e-01]
 [4.8539877e-01]
 [1.6923830e-01]
 [2.9150185e-01]
 [2.9539466e-03]
 [4.7801328e-01]
 [4.1527334e-01]
 [4.5763859e-01]
 [3.2125845e-05]
 [3.7431848e-01]]


In [26]:
test_labels = model.predict(X_test_enc)
y_predicted = test_labels

print('test_labels',test_labels[:10])

# epochs_num = 3
acc_list = []
# for i in range(epochs_num):
# loss, acc = model.evaluate(test_images, test_labels, verbose=1)
loss_acc = model.evaluate(X_test_enc, y_test_enc, verbose=1)
print('loss_acc',loss_acc)
# print('loss, acc',loss, acc)
print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))
acc_list.append('Restored model, accuracy: {:5.2f}%'.format(100 * acc))
    

test_labels [[6.1089647e-01]
 [4.8539877e-01]
 [1.6923830e-01]
 [2.9150185e-01]
 [2.9539466e-03]
 [4.7801328e-01]
 [4.1527334e-01]
 [4.5763859e-01]
 [3.2156706e-05]
 [3.7431848e-01]]
95/95 [==============================] - 0s 95us/step
loss_acc [0.750290754594301, 0.6631578978739286]


NameError: name 'acc' is not defined

In [18]:
print('X_test_enc',X_test_enc[:10])

X_test_enc [[3. 2. 4. 4. 1. 2. 0. 1. 1.]
 [3. 2. 5. 4. 1. 1. 0. 1. 1.]
 [3. 2. 7. 0. 0. 1. 0. 2. 0.]
 [2. 2. 3. 4. 1. 1. 1. 4. 1.]
 [1. 2. 0. 0. 0. 1. 1. 0. 0.]
 [1. 2. 6. 0. 0. 2. 0. 1. 0.]
 [2. 2. 5. 4. 0. 1. 1. 2. 0.]
 [1. 2. 3. 4. 1. 1. 1. 2. 1.]
 [4. 0. 2. 0. 0. 1. 1. 2. 0.]
 [3. 0. 5. 4. 0. 2. 1. 2. 0.]]


In [19]:
print('y_test_enc',y_test_enc[:10])

y_test_enc [1 0 0 1 1 1 1 0 0 1]
