In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# prepare input data
def prepare_inputs(X_train, X_test):
    oe = OrdinalEncoder()
    oe.fit(X_train)
    X_train_enc = oe.transform(X_train)
    X_test_enc = oe.transform(X_test)
    return X_train_enc, X_test_enc,oe

# prepare target
def prepare_targets(y_train, y_test):
    le = LabelEncoder()
    le.fit(y_train)
    y_train_enc = le.transform(y_train)
    y_test_enc = le.transform(y_test)
    return y_train_enc, y_test_enc,le

dataset = []

for i in range(100000):
    if i % 2 == 0:
        dataset.append(('丽丽', '美女'))
    else:
        dataset.append(('东东', '丑男'))

images = [x[0] for x in dataset]
labels = [x[1] for x in dataset]

# print(images)
# print(labels)

train_images = [[x] for x in images[:90000]]
test_images = [[x] for x in images[90000:]]
train_labels = [[x] for x in labels[:90000]]
test_labels = [[x] for x in labels[90000:]]

print(train_images[:10])
print(test_images[:10])
print(train_labels[:10])
print(test_labels[:10])

# train_images = np.array(train_images)
# test_images = np.array(test_images)
# train_labels = np.array(train_labels)
# test_labels = np.array(test_labels)

train_images, test_images,oe = prepare_inputs(train_images, test_images)
train_labels, test_labels,le = prepare_targets(train_labels, test_labels)

print(train_images.shape)

print(train_images[:10])
print(test_images[:10])
print(train_labels[:10])
print(test_labels[:10])


[['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东']]
[['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东'], ['丽丽'], ['东东']]
[['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男']]
[['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男'], ['美女'], ['丑男']]
(90000, 1)
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]
[1 0 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 1 0 1 0]


d:\python\python36\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [39]:
import keras
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(1,), activation='relu'),
    keras.layers.Dense(10, input_shape=(10,), activation='relu'),
    keras.layers.Dense(5, input_shape=(10,), activation='tanh'),
    keras.layers.Dense(1, input_shape=(5,), activation='sigmoid')
])

# model.compile(optimizer='adam',
#               loss='binary_crossentropy',metrics=['mean_absolute_error']
#              )
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#  metrics=['accuracy']

model.fit(train_images, train_labels, epochs=1)

Epoch 1/1
90000/90000 [==============================] - 5s 54us/step - loss: 0.0551 - acc: 1.0000


In [53]:
epochs_num = 10

acc_list = []

for i in range(epochs_num):

    model.fit(train_images, train_labels, epochs=1)
    weights = model.get_weights()  # Getting params
    print(weights)
    
    

Epoch 1/1
90000/90000 [==============================] - 4s 43us/step - loss: 0.0551 - acc: 1.0000
[array([[6.7179275]], dtype=float32), array([-3.2583394], dtype=float32)]
Epoch 1/1
90000/90000 [==============================] - 4s 41us/step - loss: 0.0229 - acc: 1.0000
[array([[8.481342]], dtype=float32), array([-4.1364446], dtype=float32)]
Epoch 1/1
90000/90000 [==============================] - 4s 42us/step - loss: 0.0096 - acc: 1.0000
[array([[10.220997]], dtype=float32), array([-5.0095797], dtype=float32)]
Epoch 1/1
90000/90000 [==============================] - 4s 43us/step - loss: 0.0040 - acc: 1.0000
[array([[11.9549675]], dtype=float32), array([-5.8727236], dtype=float32)]
Epoch 1/1
90000/90000 [==============================] - 4s 46us/step - loss: 0.0017 - acc: 1.0000
[array([[13.6838875]], dtype=float32), array([-6.740008], dtype=float32)]
Epoch 1/1
90000/90000 [==============================] - 4s 44us/step - loss: 7.1878e-04 - acc: 1.0000
[array([[15.410895]], dtype=floa

In [81]:
# evaluate the keras model
_, accuracy = model.evaluate(test_images, test_labels, verbose=0)
print(_)
print('Accuracy: %.2f' % (accuracy * 100))

y_predicted = model.predict(test_images[:10])
print('y_predicted',y_predicted[:10])

1.437972423445899e-05
Accuracy: 100.00
y_predicted [[9.9998701e-01]
 [1.5765429e-05]
 [9.9998701e-01]
 [1.5765429e-05]
 [9.9998701e-01]
 [1.5765429e-05]
 [9.9998701e-01]
 [1.5765429e-05]
 [9.9998701e-01]
 [1.5812300e-05]]


In [55]:
model.save('./ws_model1.h5')

## load function

In [82]:
# Loads the weights
model.load_weights('./ws_model1.h5')

In [83]:
y_predicted = model.predict(test_images)
y_predicted = y_predicted

print('test_labels',test_labels[:10])
print('test_images',test_images[:10])

test_labels [1 0 1 0 1 0 1 0 1 0]
test_images [[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [84]:
test_images

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [1.],
       [0.]])

In [87]:
test_images_or = oe.inverse_transform(test_images)
test_images_or

array([['丽丽'],
       ['东东'],
       ['丽丽'],
       ...,
       ['东东'],
       ['丽丽'],
       ['东东']], dtype=object)

In [88]:
X_train_enc = oe.transform(test_images_or)
X_train_enc

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [1.],
       [0.]])

In [102]:
a = '丽丽'
test_images_or = np.array([[a]])
X_train_enc = oe.transform(test_images_or)
X_train_enc

array([[1.]])

In [91]:
y_predicted = model.predict(X_train_enc)
y_p = [1 if x >0.5 else 0 for x in y_predicted]
y_p

[1]

In [109]:
y_p_text = le.inverse_transform(y_p)
y_p_text

array(['美女'], dtype='<U2')

In [7]:
import numpy as np

def binary_step(test_images_or,model_name):
    from tensorflow import keras
    model = keras.models.load_model(model_name)
    X_train_enc = oe.transform(test_images_or)
    y_predicted = model.predict(X_train_enc)
    y_p = [1 if x > 0.5 else 0 for x in y_predicted]
    y_p_text = le.inverse_transform(y_p)
    return y_p_text

In [8]:
a = '丽丽'
output = binary_step(np.array([[a]]),'./ws_model1.h5')
output

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


array(['美女'], dtype='<U2')

In [9]:
a = '东东'
output = binary_step(np.array([[a]]),'./rrts.h5')
output

array(['丑男'], dtype='<U2')